### PR TITLE
add flip image functionality

### PR DESCRIPTION
**Pull request by nopsqi**
sometimes there are chapters that are flipped
Screenshot_20240502_165917_Mihon
Screenshot_20240502_164846_Mihon

### CODE REVIEW

**Comment by nopsqi** [comment]
@MajorTanya yeah, but sometimes there are chapters that are flipped, so instead read from another source this will fix that

**Comment by MajorTanya** [comment]
I've genuinely never encountered or heard a user mention that their chapter images are flipped. Also, please don't make new PRs of already existing ones.

I stand by what I said in #737:
> This would mirror the text on the images as well. I don't think there is any use for this setting.

I'll keep this open for now but don't hold your breath.

**Comment by AntsyLich** [comment]
Only happens when sites are actively trying to mess with scrapers. And in the last 3 years I've only seen 3 sites do that and on all 3 cases the extension was updated to fix the issue. So no I'm not going to add this when this is fault of users poor choice extension

**Comment by nopsqi** [comment]
> I've genuinely never encountered or heard a user mention that their chapter images are flipped
ngl, it's pretty rare. "The First Ancestor in HIstory" chapter 139 from xCaliBR Scans is one of the example

> Also, please don't make new PRs of already existing ones.
mb, accidentally deleted the repo

> I'll keep this open for now but don't hold your breath.
sure, thanks

**Comment by nopsqi** [comment]
> Only happens when sites are actively trying to mess with scrapers. And in the last 3 years I've only seen 3 sites do that and on all 3 cases the extension was updated to fix the issue. So no I'm not going to add this when this is fault of users poor choice extension

ah okay, didn't know that

**Pull request closed without merging**
