### PR TITLE
Update image-decoder revision

### LINKED ISSUE #946: AVIF 10/12-bit support
### Describe your suggested feature

Mihon can't render high bit depth (more than 8 per channel) AVIFs (tested on the latest beta 0.16.5.6740).
It has no problem displaying 16-bit grayscale/48-bit RGB PNGs though.

Update 1:
Lossy and lossless JpegXLs from a 16/48 bit source do work.

Update 2:
As far as I can see, Mihon uses dav1d decoder for AVIF through libimagedecoder, and it's forced to compile with support of only 8 bits decoding: [link
](https://github.com/tachiyomiorg/image-decoder/blob/5771f6d2be486ebc4a7a232806e048a44c4a5859/library/src/main/cpp/libheif/dav1d.cmake#L16) Maybe removing -Dbitdepths=8 is all what's needed to make them work.

Update 3:
I tried to compile an apk without this option and can confirm, 10 and 12-bit AVIFs started working. Libimagedecoder size increased from 4 971 248 bytes to 5 190 416 (219 168 bytes delta) for ARM64, so it's not a big concern I think.
[Link to APK](https://1drv.ms/u/s!AkgUEzQmipA9gcdFLFjiPCfdH3nStQ?e=XQzkjH) (ARM64), if needed.
### Other details

_No response_

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.16.5](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

### PR DESCRIPTION
**Pull request by WerctFourth**
Enables >8-bit AVIF decoding.
Closes #946

### CODE REVIEW

**Comment by AntsyLich** [comment]
> Original issue: #946

Should be "Closes #XXX"

**Comment by AntsyLich** [comment]
I'll deal with the error later

**Comment by AntsyLich** [comment]
well turns out it's not the usual error so you'll have to fix the build itself on https://github.com/tachiyomiorg/image-decoder

**Comment by WerctFourth** [comment]
> well turns out it's not the usual error so you'll have to fix the build itself on https://github.com/tachiyomiorg/image-decoder

Sorry, can't figure out how to fix building in Jitpack. It was working several days ago.
Tried some things like specifying Java version (gradle starts working somewhat, but sdkmanager breaks) and such, I guess it's not that simple.
Tried to compile the library locally, it completed without errors, so nothing else broke in this time frame. APK building still works too.

**Comment by null2264** [comment]
You can bump it to `41c059e540` now :+1:

**Pull request closed without merging**
