### PR TITLE
update backup file extension

### PR DESCRIPTION
**Pull request by manuel-g-ferreira**
update backup extension file to `mihonbk`

### CODE REVIEW

**Comment by jobobby04** [comment]
Why though? Its not like we are changing the format

**Comment by manuel-g-ferreira** [comment]
was just a suggestion. In my point of view was to keep it consistent with the app name.

**Comment by jobobby04** [comment]
I don't think this is a good idea, because then all the forks have to support this new file type and that means a whole 3 file types that we need to support for people moving around.

**Comment by manuel-g-ferreira** [comment]
makes sense! great argument.

**Pull request closed without merging**
