### PR TITLE
Add PR or commit refs to CHANGELOG.md

### PR DESCRIPTION
**Pull request by MajorTanya**
Adds references to the specific PR (or commit hash if no PR was made for the change) to the Changelog file.

### CODE REVIEW

**Comment by Animeboynz** [comment]
Would it be okay to make the PR/refs clickable links?

**Comment by BrutuZ** [comment]
But, [GFM](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#referencing-issues-and-pull-requests)...

**Comment by MajorTanya** [comment]
> Would you consider making the PR/refs clickable links?

They are? GitHub will render them as dlickable links

**Comment by Animeboynz** [comment]
IDK maybe its just something weird on my side then

https://github.com/user-attachments/assets/558b9815-414a-48be-9a98-9f0d1e842053

**Comment by AntsyLich** [comment]
Mentions don't render on markdown files. Not sure about PRs and commits

**Comment by MajorTanya** [comment]
> Mentions don't render on markdown files. Not sure about PRs and commits

**Comment by AntsyLich** [comment]
release notes =/= markdown files

**Comment by Animeboynz** [comment]
Odd

https://github.com/user-attachments/assets/a0059ac8-9725-4c00-8087-b030779add41

**Comment by MajorTanya** [comment]
> > Here's what I see in the 0.16.5 release notes
> 
> Odd
> 
> https://github.com/user-attachments/assets/a0059ac8-9725-4c00-8087-b030779add41
> 
> 

Apparently that only happens in release notes, I swear it happened everywhere. Now I'm not even sure if the PRs will link eventually, that's so dumb.

**Comment by Animeboynz** [comment]
We could always just use `[]()`

**Comment by MajorTanya** [comment]
> We could always just use `[]()`

Yes, but I'll try [one other thing first](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/autolinked-references-and-urls#issues-and-pull-requests). Hoping that'll make GitHub show the short links instead of long ones.

**Comment by FooIbar** [comment]
Just use full link and it will show correctly even outside of GitHub (i.e. on the website).

**Comment by Animeboynz** [comment]
It's missing one of my commits 😤 smh
😂😂

**Comment by MajorTanya** [comment]
> It's missing one of my commits 😤 smh
> 😂😂

Which one? If it happened after the initial changelog creation, it wouldn't be in here.

**Comment by Animeboynz** [comment]
#1057

**Comment by MajorTanya** [comment]
> #1057

Technically out of scope for this PR but I'll add it later 👍

**Pull request merged**
