### PR TITLE
Disable predictive back gesture for Android 13

### LINKED ISSUE #34: Swipe Back doesnt Have Animation
### Steps to reproduce

1.- Open Mihon 
2.- You are at library
3.- Swipe back with gesture(right to left or left to right) to go at Home (Android Desktop)
4.- When i swipe back the animation doesnt appear

### Expected behavior

There should be an animation when you swipe back to go home.

### Actual behavior

There is no animation when there should be

### Crash logs

_No response_

### Mihon version

0.16.0

### Android version

Android 13

### Device

Poco X3 Pro MIUI 14

### Other details

In Tachiyomi 0.14.7 this error doesnt occur but in 0.15 yes
When you swipe from bottom to top the animation works only doesnt appear when you swipe right to left or left to right

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an official extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [x] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

### PR DESCRIPTION
**Pull request by FooIbar**
It causes flickering on some (e.g. MIUI) devices.

Closes #34

### CODE REVIEW

**Comment by AntsyLich** [comment]
Fully disabling predictive gesture on Android 13 just because MIUI broke it (like they always do with Android features) doesn't seem like the best idea to me. Even Google doesn't disable it on their apps (e.g. Calculator). Fell free to make a new PR if you can somehow disable it only for MIUI devices.

**Comment by FooIbar** [comment]
In-app predictive back animations are not available until Anroid 14 anyway.
Anroid 13 only has the back-to-home animation, and it's behind a developer option.
I think it's worth to disable it.

**Comment by AntsyLich** [comment]
I use it soooo

**Comment by FooIbar** [comment]
Just update to A14 :P

**Pull request closed without merging**
