### PR TITLE
Don't copy archives to temp files in local source

### LINKED ISSUE #134: Local archives are being fully copied to temp folder every time they're opened for reading
### Steps to reproduce

1. Have an archive (*.zip) with pictures in /local/title/ folder
2. Open the app
3. Go to Browse -> Local source -> Select the title -> Open the archive for reading
4. Open any file manager and navigate to Internal Storage/Android/Data/app.mihon/cache/tmp/
5. See the archive fully copied there under different name (*.tmp)
6. Switch back to Mihon and go back to the chapter selector
7. Switch back to the file manager and see the temp file gone

So... Why does the app do this? Why not just read the archive from a dedicated folder set on first run (Internal Storage/Mihon/local/ or something else)? What if it is a 0.5 GB archive copied and removed over and over again? This could cause unnecessary wear on flash storage.

### Expected behavior

The app should just read the archive from a dedicated folder with app data, I guess.

### Actual behavior

The app copies the archive to the tmp folder for some reason, then reads it from there, then removes, then copies it on every read.

### Crash logs

_No response_

### Mihon version

0.16.1 Stable

### Android version

Android 11

### Device

Teclast T30

### Other details

_No response_

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an official extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.16.1](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

### PR DESCRIPTION
**Pull request by FooIbar**
Closes #134

### CODE REVIEW

**Comment by AntsyLich** [comment]
Does it not make loading slower due to SAF?

**Comment by FooIbar** [comment]
I mean, we are already using SAF.
It's not like we can bypass it unless requesting `MANAGE_EXTERNAL_STORAGE`.

**Comment by FooIbar** [comment]
Benchmark for a \~340 MB archive to load on test device

Before: 4000\~5000 ms (\~80% of time on copy to temp file)
After: 1000\~1500 ms

**Comment by AntsyLich** [comment]
That's quite a bit of improvement. Seems okay to merge I guess. For the records can you also do a benchmark for some smaller sizes like ~20mb ~50mb ~100mb

**Comment by FooIbar** [comment]
| Archive size [MB] | Avg. before [ms] | Copy time | Avg. after [ms] | Diff |
|---|---|---|---|---|
| 3.27 | 1245 | 13% | 1282 | +2.9% |
| 46.8 | 1387 | 20% | 1435 | +3.5% |
| 103 | 1991 | 29% | 1789 | -10% |
| 194 | 3514 | 74% | 1238 | -65% |
| 339 | 6829 | 85% | 1408 | -79% |

**Comment by FooIbar** [comment]
Will do more tomorrow.

**Comment by FooIbar** [comment]
The results above were obtained from a 2GB RAM AVD using debug build.
It may not represent real user experience, so I did another one on a 12GB RAM physical device with release build.
| Archive size [MB] | Avg. before [ms] | Copy time | Avg. after [ms] | Diff |
|---|---|---|---|---|
| 46.8 | 110 | 26% | 96 | -13% |
| 103 | 150 | 36% | 96 | -36% |
| 194 | 199 | 60% | 95 | -52% |
| 339 | 280 | 72% | 80 | -71% |

**Comment by AntsyLich** [comment]
So apparently this doesn't work on Fold 5 and S24 Ultra

**Comment by FooIbar** [comment]
> So apparently this doesn't work on Fold 5 and S24 Ultra

Could you provide more details to illustrate it?

**Pull request merged**
