### PR TITLE
feat: Komga page-based sync

### PR DESCRIPTION
**Pull request by RandomNamer**
As mentioned in issue #236 
Page-level read progress sync for Komga based on the current Komga tracker. This is a preliminary implementation, every page turn would be reported to Komga (just like the Komga web app, no rate limit); to sync page progress from Komga, users have to refresh tracker manually (and to ensure the request completes with in the lifecycle of the dialog window).

<details>
<summary></summary>
 I was really suprised to see unlike the web app, progress syncing does not work with page indeces when I tried to use Mihon as reader for my Komga server. As I read the code I have doubts on whether multi-device progress syncing should be implemented as a type of tracker or if we need to design new solutions for syncing, e.g. within the extension. I would really like to see your opinions on this feature. 
</details>

### CODE REVIEW

**Comment by kanjieater** [comment]
> [app-dev-arm64-v8a-preview.apk.zip](https://github.com/user-attachments/files/16279777/app-dev-arm64-v8a-preview.apk.zip)

I've been enjoying using this the last few days. I did notice an issue today.

Playing around with this a bit more. It seems that it didn't sync read progress on a completed volume for some reason.

so i was on ch 161 of chainsaw man. Both mihon and komga were set as page 2. I read through 162 on mihon. Opened to page 3 of 163

In komga, 161 was still left on page page 2. 162 was left unread, and 163 was on page 3. So it seems like the competed pages, and updated page count of 161 didn't sync for some reason.

Also if i mark something as read on komga, but then start reading it on mihon, it doesn't sync the change back to komga. I marked 163 as read in komga. Then I start _reading_ 163, it doesn't seem to update the page progress.

**Comment by RandomNamer** [comment]
> so i was on ch 161 of chainsaw man. Both mihon and komga were set as page 2. I read through 162 on mihon. Opened to page 3 of 163

> I marked 163 as read in komga. Then I start _reading_ 163, it doesn't seem to update the page progress.


I'm not able to replicate both issues on my end. Have you tried to check the debug logs to see if the read-progress requests are sent as expected? Even if marked read in Mihon, that request is still expected to be sent when start reading it.

**Comment by kanjieater** [comment]
I'm looking into how to provide debug logs but failing. Happy to provide them if you could tell me how. Also happy to debug this in real time with you if you message me on discord at `kanjieater`

**Comment by RandomNamer** [comment]
You can use either `adb logcat` or Android Studio to inspect these. I just verified debug logs are not shrinked in that apk.
- adb cli: `adb logcat "*:S" "KomgaApi:D"`
image
- Android Studio: 
image

**Comment by kanjieater** [comment]
> You can use either `adb logcat` or Android Studio to inspect these. I just verified debug logs are not shrunk in that apk.
> 
> * adb cli: `adb logcat "*:S" "KomgaApi:D"`
> 
> image - Android Studio: image

Chainsaw man had no logs shown. Eyeshield 21 did show working logs though
```
D:\Program Files (x86)\scrcpy-win64>adb logcat -s "ce061716626c0b1b037e" "KomgaApi:D"
--------- beginning of main
--------- beginning of system
07-21 11:21:19.668 25012 25289 E KomgaApi: update progress to 138 with Response{protocol=h2, code=204, message=, url=https://ko.shke.xyz/api/v1/books/0GAA9F50F5PMB/read-progress}
07-21 11:21:29.577 25012 25883 E KomgaApi: update progress to 139 with Response{protocol=h2, code=204, message=, url=https://ko.shke.xyz/api/v1/books/0GAA9F50F5PMB/read-progress}
07-21 11:21:32.188 25012 25918 E KomgaApi: update progress to 138 with Response{protocol=h2, code=204, message=, url=https://ko.shke.xyz/api/v1/books/0GAA9F50F5PMB/read-progress}```

**Comment by kanjieater** [comment]
Something i haven't read like chainsaw man 165 _does_ show logs though

**Comment by RandomNamer** [comment]
> Something i haven't read like chainsaw man 165 _does_ show logs though

Currently all chapters behind your last read should be ignore from syncing. I think I can change that for page trackers.

> If you mark it as unread in komga, then sync from mihon. Mihon will overwrite whatever komga had.

This is expected, since the current trakcer uses `/api/v2/series/{seriesId}/read-progress/tachiyomi` to update the series progress to `lastBookNumberSortRead ` and  Komga will then mark all chapters prior to that as read. I'm not changing that.



> but needs to by synced with the mihon tracker open button to sync the full read vol progress

Volume read (in Komga it's called `book`) status is handled by old logic of Komga tracker and it's updated by clicking the button and  open the tracker window. All updates should be completed within the lifecycle of that Window. The app won't keep a event stream connection to the server so no real-time bidirectional sync: sync to Komga is real time, sync back is triggered when open tracker window.

**Comment by kanjieater** [comment]
@RandomNamer looks like this is closed now? I'm hoping we can keep progress rolling on this! 😊 Any chance of reopening it?

**Comment by RandomNamer** [comment]
Migrated to a new branch, did a overhual and it's now at #1032

**Pull request closed without merging**
