### PR TITLE
Fix bgm tracker showing empty due to no Chinese name

### PR DESCRIPTION
**Pull request by NeKoOuO**
### Images

| Before | After |
| ------- | ------- |
|  |

### CODE REVIEW

**Comment by AntsyLich** [comment]
I'll keep this in hold until #1103 is merged

**Comment by NeKoOuO** [comment]
> I'll keep this in hold until #1103 is merged

I know it's okay 😌

**Comment by AntsyLich** [comment]
is name not summary?

**Comment by AntsyLich** [comment]
Found some more stuff that needs fixing. i'll takeover this

**Comment by NeKoOuO** [comment]
> is name not summary?

What do you mean?

**Comment by NeKoOuO** [comment]
> Found some more stuff that needs fixing. i'll takeover this

Yep, there's also a problem since the trackers have been create, the original site have changed by adding an NSFW option for entries, so the [API](https://bangumi.github.io/api/#/) has also changed. Now, if you want to track NSFW, the website will return empty results.

**Pull request closed without merging**
